version: '2.3'

services:
  ttnbridge:
    build:
      context: .
    image: monicaproject/ttn-bridge:latest
    command: ["dotnet","./TTN-Bridge.dll"]
    ports:
      - 8080:8080
    volumes:
      - "./config:/etc/ttnbridge"