version: '2.3'

services:
  ttnbridge:
    build:
      context: .
    image: monicaproject/ttn-bridge:latest
    command: ["dotnet","./TTN-Bridge.dll"]
    volumes:
      - "./config:/etc/ttnbridge"